### ISSUE TITLE
Does bs58 add padding of any kind?

### ISSUE THREAD

**Issue by sunknudsen** [cryptocoinjs/bs58#47]
Contemplating using Base58 (via [bs58](https://github.com/cryptocoinjs/bs58)) to concatenate blocks of ciphertext with plausible deniability by design.

To achieve plausible deniability by design, blocks need to be indistinguishable from each other… as a result, using Base64 is not possible because of padding.

Does bs58 add padding of any kind?

Also, would someone happen to know why encode("foobar") is not equal to encode("foo") + encode("bar")?

```javascript
import { encode } from "bs58"

const foobar = Buffer.from("foobar")

console.log(foobar, encode(foobar))
// <Buffer 66 6f 6f 62 61 72> t1Zv2yaZ

const foo = Buffer.from("foo")
const bar = Buffer.from("bar")

console.log(Buffer.concat([foo, bar]), `${encode(foo)}${encode(bar)}`)
// <Buffer 66 6f 6f 62 61 72> bQbpa3cM

```

**Comment by junderw** [comment]
base58 encoding is basically:
1. Take an array of bytes (for text, interpret as utf8 (which is basically ascii for alphanumeric))
2. Count the number of 0x00 bytes at the left side of the array. ( leftpad = )
3. Interpret the byte array as a big endian BigInt integer. (ie. `0x1f2f3f4f` would be `523190095`)
4. loop on a divmod of that number by 58, taking the mod (0-57) and converting it to a character from the 58 character set, then using the div result for the next loop. perform this until the div result is 0.
5. Add the character `1` at the left of the result for `leftpad` times. (this will tell us how many `0x00` bytes to add back on when we decode it) Since `1` is the "zero value" of the character set. (ie. in the character set `0123456789` `0` is the zero value, which is used for zero padding (ie. `000100 === 100`)

So no, there is no padding, but your `${encode(foo)}${encode(bar)}` is basically the same as saying "101 + 202 = 101202" and is based on a fundamental misunderstanding of what this encoding method is / does.

Please let me know if you still have questions.

**Comment by junderw** [comment]
As an example, try encoding the following byte arrays:

```js
0x39 // 57
0x3a // 58
0x000039 // 57 with 2 0x00 bytes
0x00003a // 58 with 2 0x00 bytes
```

**Comment by junderw** [comment]
If you want to perfectly cut up a block of groups of 8 bits to where you can just paste two groups together without encoding/decoding, you need to split them into 4 bits (hexadecimal 0-9a-f) 2 bits (0-3) or 1 bit (0-1)

since 8 factored out is 2x2x2(x1) so the only possibilities are groups of 8, 4, 2, 1 if you want to guarantee they will never create "padding".
